// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type RuntimePublicEnv = {
  SUPABASE_URL?: string;
  SUPABASE_PUBLISHABLE_KEY?: string;
};

function getRuntimePublicEnv(): RuntimePublicEnv {
  if (typeof window === "undefined") {
    return {};
  }

  return window.__QURBANIR_HAAT_ENV__ ?? {};
}

function getProcessEnv(name: "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY") {
  if (typeof process === "undefined") {
    return undefined;
  }

  return process.env[name];
}

function createSupabaseClient() {
  const runtimePublicEnv = getRuntimePublicEnv();
  const isBrowser = typeof window !== "undefined";
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    runtimePublicEnv.SUPABASE_URL ||
    getProcessEnv("SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    runtimePublicEnv.SUPABASE_PUBLISHABLE_KEY ||
    getProcessEnv("SUPABASE_PUBLISHABLE_KEY");

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL
        ? [isBrowser ? "VITE_SUPABASE_URL or runtime SUPABASE_URL" : "SUPABASE_URL"]
        : []),
      ...(!SUPABASE_PUBLISHABLE_KEY
        ? [
            isBrowser
              ? "VITE_SUPABASE_PUBLISHABLE_KEY or runtime SUPABASE_PUBLISHABLE_KEY"
              : "SUPABASE_PUBLISHABLE_KEY",
          ]
        : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure them in the app environment and restart the server.`;
    if (!isBrowser) {
      console.error(`[Supabase] ${message}`);
    }
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
